version: '3.8'

services:
  backend:
    build: . #pour construire l'image à partir du Dockerfile
    working_dir: /app
    volumes:
      - ./back:/app
    command: ["npm", "run dev"]
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
