version: '3.8'

services:
  backend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./back:/app
    command: ["npm start"]
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
